// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmUJYTQNIk109ZrwyBLS_MiRzjal5bcB8',
    appId: '1:972061656776:android:d16cb61b4625b1eeb5c7fd',
    messagingSenderId: '972061656776',
    projectId: 'pari-gsc',
    databaseURL: 'https://pari-gsc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pari-gsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt-VLY_XvP6mDjLyoSaryK52TayIsdnk4',
    appId: '1:972061656776:ios:9346b6571f0ed7a4b5c7fd',
    messagingSenderId: '972061656776',
    projectId: 'pari-gsc',
    databaseURL: 'https://pari-gsc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'pari-gsc.appspot.com',
    iosClientId: '972061656776-cehujcedco16u1894t44mvu7ffv36fq2.apps.googleusercontent.com',
    iosBundleId: 'com.example.pariGsc',
  );
}
